export const tokens = {
  "colorPrimary": "--ak-color-primary",
  "colorPrimaryHover": "--ak-color-primary-hover",
  "colorPrimaryText": "--ak-color-primary-text",
  "colorSurface": "--ak-color-surface",
  "colorText": "--ak-color-text",
  "colorBorder": "--ak-color-border",
  "colorDanger": "--ak-color-danger",
  "space1": "--ak-space-1",
  "space2": "--ak-space-2",
  "space3": "--ak-space-3",
  "space4": "--ak-space-4",
  "space5": "--ak-space-5",
  "radiusMd": "--ak-radius-md",
  "textSm": "--ak-text-sm",
  "textMd": "--ak-text-md",
  "textLg": "--ak-text-lg",
  "fontSans": "--ak-font-sans",
} as const
