export const tokens = {
  "colorPrimary": "--ds-color-primary",
  "colorPrimaryHover": "--ds-color-primary-hover",
  "colorPrimaryText": "--ds-color-primary-text",
  "colorSurface": "--ds-color-surface",
  "colorText": "--ds-color-text",
  "colorBorder": "--ds-color-border",
  "colorDanger": "--ds-color-danger",
  "space1": "--ds-space-1",
  "space2": "--ds-space-2",
  "space3": "--ds-space-3",
  "space4": "--ds-space-4",
  "space5": "--ds-space-5",
  "radiusMd": "--ds-radius-md",
  "textSm": "--ds-text-sm",
  "textMd": "--ds-text-md",
  "textLg": "--ds-text-lg",
  "fontSans": "--ds-font-sans",
} as const
